import { StyleSheet, Dimensions } from 'react-native';
import { COLORS } from './GlobalStyles';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#35c1a7' },
  moodHeading: {
    textAlign: 'center',
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000',
    marginTop: 25,
  },
  moodRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    paddingHorizontal: 15,
  },
  arrow: {
    fontSize: 22,
    color: '#000',
    fontWeight: 'bold',
  },
  moodSelector: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    flex: 1,
  },
  moodItem: {
    alignItems: 'center',
    marginHorizontal: 5,
  },
  emojiCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  activeCircle: {
    backgroundColor: '#d4f2ec',
  },
  emoji: { fontSize: 24 },
  moodLabel: { fontSize: 12, color: '#666' },
  activeMoodLabel: { color: '#000', fontWeight: 'bold' },
  moodSubText: {
    marginTop: 10,
    marginLeft: 22,
    fontSize: 15,
    fontWeight: '500',
    color: '#000',
  },
  content: {
    padding: 15,
    backgroundColor: '#f7f7f7',
    paddingBottom: 90,
  },
  momentCard: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 12,
    marginBottom: 20,
  },
  momentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  options: {
    fontSize: 20,
    color: '#aaa',
  },
  momentDate: {
    fontWeight: 'bold',
    color: '#333',
  },
  momentLocation: {
    fontSize: 12,
    color: '#666',
  },
  caption: {
    marginBottom: 10,
    color: '#444',
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  gridImageWrap: {
    width: GRID_IMAGE_SIZE,
    height: GRID_IMAGE_SIZE,
    marginBottom: 4,
    position: 'relative',
  },
  gridImage: {
    width: '100%',
    height: '100%',
    borderRadius: 5,
  },
  overlayTextBox: {
    position: 'absolute',
    bottom: 6,
    left: 6,
    right: 6,
    backgroundColor: '#fff',
    paddingVertical: 2,
    borderRadius: 4,
  },
  overlayText: {
    fontSize: 10,
    color: '#1e7d1e',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  moreMoments: {
    marginTop: 8,
    textAlign: 'center',
    color: '#888',
    fontSize: 12,
  },
  overlayPlus: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#23C7A4aa',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  plus: {
    fontSize: 28,
    color: '#fff',
    fontWeight: 'bold',
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    width: width,
    height: 60,
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderTopWidth: 1,
    borderColor: '#ccc',
  },
  navItem: {
    fontWeight: '600',
    color: '#333',
  },
  navAdd: {
    backgroundColor: '#23C7A4',
    width: 50,
    height: 50,
    borderRadius: 25,
    marginTop: -30,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  navPlus: {
    fontSize: 24,
    color: '#fff',
  },
  modalOverlay: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'rgba(0,0,0,0.6)',
  justifyContent: 'center',
  alignItems: 'center',
  zIndex: 99,
},
modalBackground: {
  position: 'absolute',
  width: '100%',
  height: '100%',
},
fullImage: {
  width: '90%',
  height: '60%',
  resizeMode: 'contain',
  borderRadius: 10,
},
});